#!/bin/bash

if [ $# = "1" ] ; then
  
  if [ $1 = "superrugby" ] ; then
    mplayer "http://radionetworknz.streamguys.com/rsonline/rsonline.stream/playlist.m3u8"
    #mplayer "http://85.10.196.144/capetalk-live"
  fi

  if [ $1 = "capetalk" ] ; then
    mplayer "http://46.4.25.237/capetalk-live"
    #mplayer "http://85.10.196.144/capetalk-live"
  fi

  if [ $1 = "5fm" ] ; then
    mplayer "http://196.35.68.110/5fm_22"
  fi

  if [ $1 = "radio2000" ] ; then
    mplayer "http://216.246.37.51/pbs-radio2000-live"
    #mplayer "rtsp://196.35.68.246/radio2000-live"
    #mplayer "http://196.33.130.40/radio2000-live"
  fi

  if [ $1 = "kfm" ] ; then
    mplayer "http://196.35.64.36/kfm_22"
  fi

  if [ $1 = "highveld" ] ; then
    mplayer "http://196.35.64.36/highveld_22"
  fi

  if [ $1 = "uct" ] ; then
    mplayer "http://188.138.56.4:8130"
  fi

else

  echo "only one argument needed"
  echo "Options 5fm, kfm, capetalk, radio2000"

fi
